//
// BaseRolloutStrategyAttribute.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BaseRolloutStrategyAttribute: Codable, JSONEncodable, Hashable {

    public var conditional: RolloutStrategyAttributeConditional?
    public var fieldName: String?
    /** the value(s) associated with this rule */
    public var values: [AnyCodable]?
    public var type: RolloutStrategyFieldType?

    public init(conditional: RolloutStrategyAttributeConditional? = nil, fieldName: String? = nil, values: [AnyCodable]? = nil, type: RolloutStrategyFieldType? = nil) {
        self.conditional = conditional
        self.fieldName = fieldName
        self.values = values
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case conditional
        case fieldName
        case values
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(conditional, forKey: .conditional)
        try container.encodeIfPresent(fieldName, forKey: .fieldName)
        try container.encodeIfPresent(values, forKey: .values)
        try container.encodeIfPresent(type, forKey: .type)
    }
}

