//
// FeatureValueType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum FeatureValueType: String, Codable, CaseIterable {
    case boolean = "BOOLEAN"
    case string = "STRING"
    case number = "NUMBER"
    case json = "JSON"
}
