//
// FeatureStateUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FeatureStateUpdate: Codable, JSONEncodable, Hashable {

    /** the new value */
    public var value: AnyCodable?
    /** indicates whether you are trying to update the value, as value can be null */
    public var updateValue: Bool?
    /** set only if you wish to lock or unlock, otherwise null */
    public var lock: Bool?

    public init(value: AnyCodable? = nil, updateValue: Bool? = nil, lock: Bool? = nil) {
        self.value = value
        self.updateValue = updateValue
        self.lock = lock
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case value
        case updateValue
        case lock
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(value, forKey: .value)
        try container.encodeIfPresent(updateValue, forKey: .updateValue)
        try container.encodeIfPresent(lock, forKey: .lock)
    }
}

