//
// FeatureEnvironmentCollection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** This represents a collection of features as per a request from a GET api. GET&#39;s can request multiple API Keys at the same time. */
public struct FeatureEnvironmentCollection: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var features: [FeatureState]?

    public init(id: UUID, features: [FeatureState]? = nil) {
        self.id = id
        self.features = features
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case features
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(features, forKey: .features)
    }
}

