//
// RolloutStrategyAttributeConditional.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum RolloutStrategyAttributeConditional: String, Codable, CaseIterable {
    case equals = "EQUALS"
    case endsWith = "ENDS_WITH"
    case startsWith = "STARTS_WITH"
    case greater = "GREATER"
    case greaterEquals = "GREATER_EQUALS"
    case less = "LESS"
    case lessEquals = "LESS_EQUALS"
    case notEquals = "NOT_EQUALS"
    case includes = "INCLUDES"
    case excludes = "EXCLUDES"
    case regex = "REGEX"
}
