//
// SSEResultState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** error is an inherent state */
public enum SSEResultState: String, Codable, CaseIterable {
    case ack = "ack"
    case bye = "bye"
    case failure = "failure"
    case features = "features"
    case feature = "feature"
    case deleteFeature = "delete_feature"
    case config = "config"
    case error = "error"
}
