//
// StrategyAttributePlatformName.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum StrategyAttributePlatformName: String, Codable, CaseIterable {
    case linux = "linux"
    case windows = "windows"
    case macos = "macos"
    case android = "android"
    case ios = "ios"
}
