//
// InfoServiceAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class InfoServiceAPI {

    /**

     - returns: ApplicationVersionInfo
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getInfoVersion() async throws -> ApplicationVersionInfo {
        return try await getInfoVersionWithRequestBuilder().execute().body
    }

    /**
     - GET /info/version
     - Gets information as to what this server is.
     - returns: RequestBuilder<ApplicationVersionInfo> 
     */
    open class func getInfoVersionWithRequestBuilder() -> RequestBuilder<ApplicationVersionInfo> {
        let localVariablePath = "/info/version"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ApplicationVersionInfo>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
