//
// RoleType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum RoleType: String, Codable, CaseIterable {
    case read = "READ"
    case lock = "LOCK"
    case unlock = "UNLOCK"
    case changeValue = "CHANGE_VALUE"
}
