//
// StrategyAttributeDeviceName.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum StrategyAttributeDeviceName: String, Codable, CaseIterable {
    case browser = "browser"
    case mobile = "mobile"
    case desktop = "desktop"
    case server = "server"
    case watch = "watch"
    case embedded = "embedded"
}
