//
// StrategyAttributeWellKnownNames.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum StrategyAttributeWellKnownNames: String, Codable, CaseIterable {
    case device = "device"
    case country = "country"
    case platform = "platform"
    case userkey = "userkey"
    case session = "session"
    case version = "version"
}
