name: Build featurehub-javascript-client-sdk

# Controls when the action will run.
on:
  # Triggers the workflow on push request events but only for the master branch
  pull_request:
    branches: [ main ]
    paths:
    - 'featurehub-swift-sdk/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Get swift version
        run: swift --version
      - name: Run tests
        run: swift test
        working-directory: featurehub-swift-sdk
